### ISSUE TITLE
`npm start` does not work

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-react-boilerplate#109]
https://github.com/vporton/courts/commit/3465d94614dbddda37d82d2992c155da17678b05
```
npm start
...
Compiled 87 contracts successfully
backend  | Contracts compiled.
backend  | Started a ganache testnet instance with id 1590072386592.
backend  | Deploying Aragon bases (ENS, DAOFactory, and APM)...
backend  | ENS deployed: 0x5f6F7E8cc7346a11ca2dEf8f827b7a0b612c56a1
backend  | DAO factory deployed: 0x8EEaea23686c319133a7cC110b840d1591d9AeE0
backend  | APM deployed: 0xA53dE0b8e08b798f975D57f48384C177D410d170
backend  | Deploying DAO and app repository...
backend  | DAO deployed: 0x0D13999edC23D3475Ed3FE22a15Cc7828FeCD762
backend  | Creating app...
backend  | Proxy address: 0xA1A7d254552BEB05f15522EeD93B54441E61d1d9
backend  | Repo address: 0xAaFe10d42Afa9cAf22AEA3E853afD6EB279B6544
backend  | Proxy init params: 42
backend  | Implementation address: 0xbcE9e0203B700f9382C66405Dc5b4687E2e5F0A0
backend  | App version: 1,0,0
backend  | Initializing proxy...
An unexpected error occurred:

Error: Invalid number of parameters for "initialize". Got 1 expected 0!    at PromiEvent (/home/porton/Projects/courts/node_modules/@nomiclabs/truffle-contract/lib/promievent.js:13:30)
    at TruffleContract.initialize (/home/porton/Projects/courts/node_modules/@nomiclabs/truffle-contract/lib/execute.js:169:26)
    at Object.startBackend (/home/porton/Projects/courts/node_modules/@aragon/buidler-aragon/src/tasks/start/start-backend.ts:130:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at SimpleTaskDefinition.action (/home/porton/Projects/courts/node_modules/@aragon/buidler-aragon/src/tasks/start-task.ts:68:11)
    at Environment._runTaskDefinition (/home/porton/Projects/courts/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:196:14)
    at main (/home/porton/Projects/courts/node_modules/@nomiclabs/buidler/src/internal/cli/cli.ts:151:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @porton/apps-judge@5.0.1 start: `buidler start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @porton/apps-judge@5.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/porton/.npm/_logs/2020-05-21T14_46_30_962Z-debug.log
```

**Comment by macor161** [comment]
Hi @vporton, this question would be better suited for our [Spectrum server](https://spectrum.chat/aragon). I'm closing this issue but I invite you to open a thread on Spectrum.
